package com.example.fortune_cookies_app.controller;

import com.example.fortune_cookies_app.model.*;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;

import java.time.LocalDate;
import java.time.YearMonth;
import java.util.Comparator;
import java.util.List;

public class DefaultSidebarController {
    public Button saveMessage;
    @FXML
    private VBox eventsList;
    @FXML
    private Label loginStreakLabel;
    @FXML
    private TextArea aiDailyMessage;


    private final EventDAO eventDAO = new EventDAO();
    private final AIMessageDAO MessageDAO = new AIMessageDAO();
    private String currentMessage;
    private User user;
    private YearMonth currentMonth;
    /**
     * Sets the current user and populate/refreshes the calendar
     * @param user - user
     */
    public void setUser(User user) {
        this.user = user;
        tryLoadEvents();
    }

    /**
     * Sets the current month of the sidebar data so correct events can be pulled
     * @param currentMonth The current month
     */
    public void setCurrentMonth(YearMonth currentMonth) {
        this.currentMonth = currentMonth;
        tryLoadEvents();
    }

    private void tryLoadEvents() {
        if (user != null && currentMonth != null && eventsList != null) {
            loadEvents();
            loadAIDailyMessage();
        }
    }

    /**
     * loads all the user events into the sidebar and includes the title
     * as additional information including the importance colour.
     */
    public void loadEvents(){
        System.out.println("Loading events into default sidebar...");
        System.out.println("User = " + (user != null ? user.getId() : "null"));
        System.out.println("Month = " + (currentMonth != null ? currentMonth.toString() : "null"));
        if (user == null || currentMonth ==null)
            return;
        eventsList.getChildren().clear();

        List<Event> events = eventDAO.fetchEvents(user);
        for (Event event: events) {
            LocalDate eventDate = event.getDate();
            YearMonth eventMonth = YearMonth.from(eventDate);
            System.out.println("Comparing eventMonth=" + eventMonth + " to currentMonth=" + currentMonth);

            if (eventMonth.equals(currentMonth)) {
                System.out.println("Matched! Adding: " + event.getEventName());
            } else {
                System.out.println("Skipped event: " + event.getEventName());
            }
            if(eventMonth.equals(currentMonth)) {
                HBox eventItem = new HBox(8);
                eventItem.setPrefHeight(24);
                Region circle = new Region();
                circle.setStyle("-fx-background-color: " + getImportanceColour(event.getImportance()) + "; -fx-background-radius: 50%;");
                circle.setMinSize(20, 20);
                circle.setPrefSize(20, 20);
                circle.setMaxSize(20, 20);

                Label eventTitle = new Label(event.getEventName());
                eventTitle.setStyle("-fx-font-size: 14;");
                eventItem.getChildren().addAll(circle, eventTitle);
                eventsList.getChildren().add(eventItem);

            }
        }


    }

    /**
     *  Loads the AI daily message based on the next upcoming event and updates the TextArea
     *  with a daily motivational message generated by the AI.
     * <p>
     * The prompt instructs the AI to generate a short, uplifting daily message for the next event
     * without any follow-up questions or multiple options.
     * </p>>
     */
    private void loadAIDailyMessage(){
        System.out.println("AI loading…");
        LocalDate today = LocalDate.now();
        eventDAO.fetchEvents(user).stream()
                .filter(e -> !e.getDate().isBefore(today))
                .min(Comparator.comparing(Event::getDate))
                .ifPresent(next -> {
                    aiDailyMessage.setText("Thinking about ‘" + next.getEventName() + "’…");
                    String prompt = String.format(
                            "Give me a short, uplifting daily message for my next event ‘%s’ on %s. dont ask questions just give me a motivational message and never multiple options.",
                            next.getEventName(), next.getDate()
                    );
                    OllamaClient.askAsync(prompt, response -> {
                        String reply = (response != null && response.getResponse() != null)
                                ? response.getResponse()
                                : "AI returned no message.";
                        Platform.runLater(() -> aiDailyMessage.setText(reply));
                        currentMessage = reply;
                    });
                });
    }
    private String getImportanceColour(int level) {
        return switch (level) {
            case 1 -> "#bbdefb";
            case 2 -> "#c8e6c9";
            case 3 -> "#fff9c4";
            case 4 -> "#e1bee7";
            case 5 -> "#ffcdd2";
            default -> "lightgrey";
        };
    }


    public void onSaveMessageClick() {
        AIMessage newMessage = new AIMessage(user.getId(), currentMessage);
        MessageDAO.saveMessage(newMessage);
    }
}